version: '3'

services:
  city_selector:
    build:
      context: ./city_selector  # Path to the city_selector Django project
    ports:
      - "8000:8000"
    volumes:
      - ./city_selector:/app
    command: python manage.py runserver 0.0.0.0:8000

  hyderabad:
    build:
      context: ./hyderabad  # Path to the hyderabad Django project
    ports:
      - "8001:8000"
    volumes:
      - ./hyderabad:/app
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.pem --key-file key.pem

  kochi:
    build:
      context: ./kochi  # Path to the kochi Django project
    ports:
      - "8002:8000"
    volumes:
      - ./kochi:/app
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.pem --key-file key.pem
